name: cdn
services:
    mariadb:
        image: mariadb
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: cdn
            MYSQL_PASSWORD: cdn
            MYSQL_USER: cdn
            MYSQL_DATABASE: cdn
        volumes:
            - mariadb:/var/lib/mysql
    redis:
        image: redis:latest
        restart: always
        ports:
        - "6379:6379"
        volumes:
        - redis:/root/redis
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
        - REDIS_PASSWORD=cdn
        - REDIS_PORT=6379
        - REDIS_DATABASES=16
    web:
        env_file:
            - "./.env"
            - "./frontend/.env"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: unless-stopped
volumes:
    mariadb: ~
    redis: ~
